// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { JobProvider } from "./context/JobContext";
import { UserProvider } from "./context/UserContext";
import NavBar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
    <html lang="en">
      <head>
        <title>Job Portal</title>
      </head>
      <body className={inter.className}>
        <header className="bg-gray-800 text-white p-4">
          <nav className="container mx-auto flex justify-between items-center">
            <div className="text-xl font-bold">Job Portal</div>
            
            <NavBar/>
            
          </nav>
        </header>
        <JobProvider>
        <main className="container mx-auto p-4">{children}</main>
        </JobProvider>
        <footer className="bg-gray-800 text-white p-4 text-center">
          Footer Content
        </footer>
      </body>
    </html>
    </UserProvider>
  );
}
